### ISSUE TITLE
I know its been a long time But do you remember any NOTEs about Selective-VPN usage

### ISSUE THREAD

**Issue by bmullan** [Ranlvor/Selective-VPN#1]
It looks somehwat interesting but for the life of me I don't know how to interpret some of what its doing with out a few comments etc?

I know you wrote it a long time ago but I thought I'd ask.

thanks

**Comment by Ranlvor** [comment]
What exactly is unclear?

The conecept of this script is that I want to use VPN for some of my packets but not all of them.

Linex 5-8 set up Iptables-Rules to mark all packets that should get routed via VPN.

Lines 11-12 set up a new routing table named „special“ which should be used for all marked packets.
Line 13 adds a default route to this table. All packets marked by iptables will use this new default route.

Line 15 activates NAT for my VPN-Interface because otherwise I'd try to use my default-interface-IP-Addresses inside the VPN which does not work.

Line 18 deactivates the return path filter on my VPN interface, I do not remember why.

Lines 21-23 modify my main routing table to not use the VPN.

**Comment by bmullan** [comment]
Thanks line 15 & line 18 were stumping me as to what they did or why.

Thanks! And Happy New Year !
